[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "day1"
path = "Day_1/main.rs"

[[bin]]
name = "day2"
path = "Day_2/main.rs"

[[bin]]
name = "day3"
path = "Day_3/main.rs"

[[bin]]
name = "day4"
path = "Day_4/main.rs"



[dependencies]
